/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"
#include "gpio.h"
#include "i2c.h"
#include <string.h>

uint8_t tx[] = "Hello";
uint8_t rx[34];
uint8_t tx_len = 0;
volatile uint8_t tx_done = 0;
volatile uint8_t led_flag = 0;

#define SLAVE_ADDR 0x55

void Delay(void){for(volatile uint32_t i = 0; i < 250000; i++);}

void Button_Init(void){
    GPIO_Handle_t button;

    button.pGPIOx = GPIOE;
    GPIO_ClockControl(GPIOE, ENABLE);

    button.GPIOx_CFG.pin_number = GPIO_PIN_3;
    button.GPIOx_CFG.pin_mode = GPIO_MODE_IN;
    button.GPIOx_CFG.pin_speed = GPIO_OSPEED_HIGH;
    button.GPIOx_CFG.pin_pu_pd_ctrl = GPIO_PIN_PU;

    GPIO_Init(&button);
}

void LED_Init(void){
    GPIO_Handle_t led;

    led.pGPIOx = GPIOA;
    GPIO_ClockControl(GPIOA, ENABLE);

    led.GPIOx_CFG.pin_number = GPIO_PIN_7;
    led.GPIOx_CFG.pin_mode = GPIO_MODE_OUT;
    led.GPIOx_CFG.pin_op_type = GPIO_OUT_PP;
    led.GPIOx_CFG.pin_pu_pd_ctrl = GPIO_NO_PUPD;
    led.GPIOx_CFG.pin_speed = GPIO_OSPEED_HIGH;

    GPIO_Init(&led);
    GPIO_WritePin(GPIOA, GPIO_PIN_7, SET);
}

void I2C2_GPIO_Init(void){
    GPIO_Handle_t i2c_gpio;

    i2c_gpio.pGPIOx = GPIOB;
    GPIO_ClockControl(GPIOB, ENABLE);

    i2c_gpio.GPIOx_CFG.pin_mode = GPIO_MODE_ALT_FN;
    i2c_gpio.GPIOx_CFG.pin_alt_func_mode = 4;
    i2c_gpio.GPIOx_CFG.pin_op_type = GPIO_OUT_OPDRN;
    i2c_gpio.GPIOx_CFG.pin_speed = GPIO_OSPEED_HIGH;
    i2c_gpio.GPIOx_CFG.pin_pu_pd_ctrl = GPIO_PIN_PU;

    //SDA
    i2c_gpio.GPIOx_CFG.pin_number = GPIO_PIN_11;
    GPIO_Init(&i2c_gpio);

    //SCL
    i2c_gpio.GPIOx_CFG.pin_number = GPIO_PIN_10;
    GPIO_Init(&i2c_gpio);
}

I2C_Handle_t i2c2;

void I2C2_EV_IRQHandler(void) { I2C_IRQ_EV_Handler(&i2c2); }
void I2C2_ER_IRQHandler(void) { I2C_IRQ_ER_Handler(&i2c2); }

void I2C2_Init(void){
    i2c2.pI2Cx = I2C2;

    I2C_ClockControl(I2C2, ENABLE);

    i2c2.I2C_Config.I2C_AckControl = I2C_ACK_ENABLE;
    i2c2.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_SM;
    i2c2.I2C_Config.I2C_FMDutyCycle = I2C_FM_DUTY_2;

    I2C_Init(&i2c2);
}

void I2C_ApplicationEventCallback(I2C_Handle_t *pI2C_Handle, uint8_t event){
	if(event == I2C_EV_TX_CMPLT){
		I2C_Master_Receive(&i2c2, rx, 33, SLAVE_ADDR, I2C_SR_EN);
	}else if(event == I2C_EV_RX_CMPLT){
		led_flag = 1;
		tx_done = 1;
	}else if(event == I2C_ERROR_AF){
		led_flag = 3;
		I2C_GenerateStopCondition(I2C2);
		I2C_CloseReception(&i2c2);
	}else{
		led_flag = 4;
		tx_done = 0;
	}
}

int main(void){
	tx_len = strlen((char*)tx);
	tx_done = 0;

	Button_Init();
	LED_Init();
	I2C2_GPIO_Init();
	I2C2_Init();

	I2C_IRQ_InterruptConfig(IRQ_NO_I2C2_EV, ENABLE);
	I2C_IRQ_InterruptConfig(IRQ_NO_I2C2_ER, ENABLE);

	I2C_PeripheralControl(I2C2, ENABLE);
	I2C_AckControl(I2C2, I2C_ACK_ENABLE);

	Delay();
	Delay();
	Delay();

	while(1){
	        while(GPIO_ReadPin(GPIOE, GPIO_PIN_3) == 1);
	        Delay();
	        while(GPIO_ReadPin(GPIOE, GPIO_PIN_3) == 0);
	        Delay();

	        I2C_Master_Transmit_IT(&i2c2, tx, tx_len, SLAVE_ADDR, I2C_SR_EN);

	        while(i2c2.TxRxState != I2C_READY);

	        if(led_flag >= 1){
	            uint8_t blinks = led_flag;
	            led_flag = 0;
	            for(uint32_t i = 0; i < blinks; i++){
	                GPIO_WritePin(GPIOA, GPIO_PIN_7, RESET);
	                Delay();
	                GPIO_WritePin(GPIOA, GPIO_PIN_7, SET);
	                Delay();
	            }
	      }
	}
}
